FROM ubuntu:latest
RUN apt-get update && apt-get install -y openssh-server nano
RUN echo 'root:root' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN mkdir /var/run/sshd
EXPOSE 22
CMD ["service", "ssh", "start"] && tail -f /dev/null